import Head from "next/head";
import WithNavBar from "~/components/UI/with-nabvar";

import Recipes from "~/components/recipes";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithNavBar>
        <main className="flex flex-col">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
            <div className="flex flex-col items-center gap-2">
              <Recipes />
            </div>
          </div>
        </main>
      </WithNavBar>
    </>
  );
}
